// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Table circuit {
  circuit_id bigint [primary key]
  circuit_name varchar
  country varchar
  track_type varchar
  track_length_km double
}

Table event {
    event_id bigint [pk]
    circuit_id bigint [ref: > circuit.circuit_id]
    season int
    event_name varchar
}

Table session {
  session_id bigint [pk]
  event_id bigint [ref: > event.event_id]
  session_type varchar
}

Table lap {
  lap_id bigint [primary key]
  driver_id bigint [ref: > driver.driver_id]
  constructor_id bigint [ref: > constructor.constructor_id]
  session_id bigint [ref: > session.session_id]
  lap_time_seconds double
  lap_number integer
  tyre_id bigint [ref: > tyres.tyre_id]
  tyre_age integer
  pit_in_time_seconds  double
  pit_out_time_seconds  double
  lap_start_time_seconds  double
  created_at timestamp
}

Table driver {
  driver_id bigint [pk]
  first_name varchar
  last_name varchar
  date_of_birth date
  nationality varchar
}

Table constructor {
  constructor_id bigint [pk]
  constructor_name varchar
  nationality varchar
}

Table tyres {
  tyre_id bigint [pk]
  compound  varchar
}

Table session_result {
  result_id bigint [pk]
  session_id bigint [ref: > session.session_id]
  driver_id bigint [ref: > driver.driver_id]
  constructor_id bigint [ref: > constructor.constructor_id]
  start_position integer
  finish_position integer
  finish_status varchar
  points double
}

Table weather_observation {
  weather_id bigint [pk]

  session_id bigint [ref: > session.session_id]

  observed_at_seconds double

  air_temperature double
  track_temperature double
  humidity double
  rainfall boolean
  wind_speed double
  wind_direction integer
}

